### ISSUE TITLE
`polkdaot-js-tool metadata` error

### ISSUE THREAD

**Issue by ghzlatarev** [polkadot-js/tools#367]
Hi I'm working on a Ubuntu 20.04 machine and running a local `rococo-local` node by downloading the latest polkadot binary from https://github.com/paritytech/polkadot/releases/tag/v0.9.19 and launching with ` ./polkadot --chain=rococo-local` .
Then running:
`docker run --network host jacogr/polkadot-js-tools metadata wss://rococo-rpc.polkadot.io ws://localhost:9944`

This used to work until few weeks ago, but is now producing the following output:
```
Running:
Unable to find image 'jacogr/polkadot-js-tools:latest' locally
docker run --network host jacogr/polkadot-js-tools metadata wss://rococo-rpc.polkadot.io ws://localhost:9944
latest: Pulling from jacogr/polkadot-js-tools
08a6abff8943: Already exists
9f30e4bbbf70: Pulling fs layer
0c559ff827a6: Pulling fs layer
f62e288e89c9: Pulling fs layer
f301a941b59d: Pulling fs layer
e5de09ad65b6: Pulling fs layer
f301a941b59d: Waiting
e5de09ad65b6: Waiting
0c559ff827a6: Verifying Checksum
0c559ff827a6: Download complete
f62e288e89c9: Verifying Checksum
f62e288e89c9: Download complete
e5de09ad65b6: Download complete
9f30e4bbbf70: Verifying Checksum
9f30e4bbbf70: Download complete
f301a941b59d: Verifying Checksum
f301a941b59d: Download complete
9f30e4bbbf70: Pull complete
0c559ff827a6: Pull complete
f62e288e89c9: Pull complete
f301a941b59d: Pull complete
e5de09ad65b6: Pull complete
Digest: sha256:f7fa0573a007536441bafb6a090781baa10e6b2fd1650fc8d83a6cdfb39c9ed5
Status: Downloaded newer image for jacogr/polkadot-js-tools:latest
internal/modules/cjs/loader.js:456
      throw e;
      ^

Error: Cannot find module '/usr/lib/node_modules/@polkadot/metadata-cmp/node_modules/@polkadot/types/cjs/metadata/util.js'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:922:15)
    at resolveExports (internal/modules/cjs/loader.js:450:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/usr/lib/node_modules/@polkadot/metadata-cmp/cjs/runcli.js:11:[13](https://github.com/ghzlatarev/r1cs-tutorial/runs/6093606711?check_suite_focus=true#step:5:13))
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/usr/lib/node_modules/@polkadot/metadata-cmp/node_modules/@polkadot/types/package.json'
}
```

What could be causing this ?

**Comment by dvdplm** [comment]
We are also affected by this in CI.

**Comment by joao-paulo-parity** [comment]
Here are my debugging steps

Clone the image:

```sh
docker pull jacogr/polkadot-js-tools:latest
```

Create a temporary container and copy the faulty module from it into the current folder:

```sh
docker container create --name tmp jacogr/polkadot-js-tools:latest
docker container cp tmp:/usr/lib/node_modules/@polkadot/metadata-cmp .
```

Now go by the error message:

```
Cannot find module '/usr/lib/node_modules/@polkadot/metadata-cmp/node_modules/@polkadot/types/cjs/metadata/util.js'
  at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
```

Removing the global installation prefix `/usr/lib/node_modules`, plus the path we copied from the Docker image `@polkadot/metadata-cmp`, you end up with `node_modules/@polkadot/types/cjs/metadata/util.js`. Trying to find that path:

```sh
cd metadata-cmp
ls node_modules/@polkadot/types/cjs/metadata/util.js
> ls: cannot access 'node_modules/@polkadot/types/cjs/metadata/util.js': No such file or directory
```

This demonstrates that the path does not exist, but `node_modules/@polkadot/types/cjs/metadata/util/index.js` does exist. `util` is a folder, not a file module.

The problem seems to be that the `index.js` inside the `util` folder (which is a directory, not a file module) is not being considered during import resolution. I think it has to do with [ESM Module resolution requiring mandatory file extensions](https://nodejs.org/api/esm.html#mandatory-file-extensions) and therefore it doesn't look for `index.js` inside of the directory (which would be [CommonJS module resolution](https://nodejs.org/api/modules.html#all-together)).

**Comment by joao-paulo-parity** [comment]
Here's a hack to make the image run (of course it's not a permanent solution): https://github.com/joao-paulo-parity/polkadot-js-tools/commit/619321ffe0451eba95ab936636010b294e9643df

The problematic line is `var _util = require("@polkadot/types/cjs/metadata/util");` from `/usr/lib/node_modules/@polkadot/metadata-cmp/cjs/runcli.js`. It should be `require("@polkadot/types/cjs/metadata/util/index")` instead or the resolution needs to be fixed to take `/index` into account.

**Comment by jacogr** [comment]
The extension doesn't come into play here - it is a commonjs path (the /cjs/package.js has `"type": "commonjs"`).
