### ISSUE TITLE
Signer:submit sent 3 copies of a transaction to the queue

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/tools#77]
I ran `signer submit` and the same transaction landed 3 times. Signer output below, no unusual logs from the Polkadot client.

The [address on Polkascan](https://polkascan.io/pre/kusama-cc3/account/HQyrEm6UQYpacuf8DPEFi5P3Jg1KV5G1MNjasFjWysqeGJP#transactions) shows  three transactions, all with the same hash. One shows as successful and the other two failed.

Checking the [block on Polkascan](https://polkascan.io/pre/kusama-cc3/block/296346#transactions) shows two transactions.

[Polkadot JS Apps UI](https://polkadot.js.org/apps/#/explorer/query/0x6fc6a47811546fdb93c9e7012cf523b6130134c93b6f2027c152cdff2fb31cc6) also shows two transactions.

Potential tx queue/block builder issue for putting the same tx twice in a block. CC @tomusdrw

```
> yarn run:signer submit --account HQyrEm6UQYpacuf8DPEFi5P3Jg1KV5G1MNjasFjWysqeGJP --ws ws://127.0.0.1:9944 balances.transfer Gbuksma2CxcuYVZx2upsCXbAFgZMbJgAYGeHGmzdcJtFhX5 38900000000
yarn run v1.21.1
$ ./packages/signer-cli/src/index.js submit --account HQyrEm6UQYpacuf8DPEFi5P3Jg1KV5G1MNjasFjWysqeGJP --ws ws://127.0.0.1:9944 balances.transfer Gbuksma2CxcuYVZx2upsCXbAFgZMbJgAYGeHGmzdcJtFhX5 38900000000
Payload: 0x0400ffb227708d3f91605cf2b478ab13c62a1728dc295801a0dfa369aa239dbdebef060700e59e0e095503000007040000b0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe3aa3bdaa09091e96857edc47fa6948fee4dd367a072692344e1d21e1952dce4b
Signature> 0x01ecc268ce2346974a84554cbd436f500d33f20f793c2921502d522cf6f0893557d20adf8cbfdd964c96c99ee2b7dfc1f10dd5a94ae214412d8057043b5ef9cc05
{"events":[],"status":{"Ready":null}}
{"events":[],"status":{"Broadcast":["QmNMnvHwzcEduxkWGHWBX5dxURb29MnP1e47tSc6F82Pg8","QmYG1YUekKETmD68yFKbjXDRbSAFULRRJpb1SbQPuSKA87","QmYJ6bWigUYQGsbKwPWPC9NiRzk3GjFHbQbLkC4Dq8ucJx","QmeDcYgHikD2GF56tPeMwMeCCZrUo5KP6PWtc9T3eX8bNT","QmbzbmF7nUb3bJ2Eo5CXqsWhnbRCDSFmG16JRJV44fVktg","QmYJPEifJ4PqK5eXuWMjaY3JyWVpM6QKNvtiVdwzgEcLjH","QmdePe9MiAJT4yHT2tEwmazCsckAZb19uaoSUgRDffPq3G","QmSd2eqH9xWKoEQrz5aBbKQZ56ATmvAhY9vvDQXCcFs9kW","Qmf58BhdDSkHxGy1gX5YUuHCpdYYGACxQM3nGWa7xJa5an","QmchDJtEGiEWf7Ag58HNoTg9jSGzxkSZ23VgmF6xiLKKsZ","Qmf6hguiVL9AY6SkiLBusQuNuygm4DVkxR6JrU9nKcbWMY","QmQv5EXUAfVt4gbupiuLDZP2Gd7ykK6YuXoYPkyLfLtJch","QmT9BfDUUPZtVj4HvNiE66h97BN17c1yc6yAUX1yemti2x","QmTMwRv17S17kR8aVHy7BJt6UfSzVJ34McYdQMu8EP5zYm","QmXK41VPfivoADh9XdxZqk5BmfZExb3tpXNU5fLjf1p2sd","QmeCit3Nif4VfNqrEJsdYHZGcKzRCnZvGxg6hha1iNj4mk","QmbHRBWG249kGRTzGt17hN9s4t6ZC88uW7GCGsfZPfgB1q","QmeqnCXZEzErHTCt7DvQWPcAXtLosnyr6serunAayBLeDq","QmXibkgzRfVXqiSu634dnTdNxM6EXWth7F5xnVxyctH4zQ","QmeMci8JoHpHYGVqHPQZJ88jDv7enq8D9CTy1T4EPTgJAU","QmXXnnBQQPydZYdWq4meejmEE7bJXPy7w76qSvELi7GeXD","QmW2bA5UovPGDVEZetx9dr56F93AwhNQvvVGPKzNDN875M","QmQi52uLQSAPq4NGtGSSUQ76QQTPmtC6Q3TotmpS7UbyS3","QmP3zYRhAxxw4fDf6Vq5agM8AZt1m2nKpPAEDmyEHPK5go","QmNzUMki9QH1tp6dnHsx52sYAAwRCHBZz2r43nEvuR9Pdb"]}}
{"events":[{"phase":{"ApplyExtrinsic":2},"event":{"index":"0x0201","data":["HQyrEm6UQYpacuf8DPEFi5P3Jg1KV5G1MNjasFjWysqeGJP",1000000000]},"topics":[]},{"phase":{"ApplyExtrinsic":2},"event":{"index":"0x0202","data":["HQyrEm6UQYpacuf8DPEFi5P3Jg1KV5G1MNjasFjWysqeGJP","Gbuksma2CxcuYVZx2upsCXbAFgZMbJgAYGeHGmzdcJtFhX5",38900000000,100000000]},"topics":[]},{"phase":{"ApplyExtrinsic":2},"event":{"index":"0x0000","data":[{"weight":1000000,"class":0,"paysFee":true}]},"topics":[]}],"status":{"Finalized":"0x98f57772c4f30062a471505e0b1b33c3a5dfd307e14eca38ea746f2977307ae2"}}
Done in 217.51s.
```

**Comment by tomusdrw** [comment]
Hmm, definitely an interesting situation, so the way I understand that:
1. The first inclusion (block 296345) caused the balance to drop below ED
2. That caused the account to be reaped (there is an event for that), so the nonce was reset back to 0.
3. Since transaction culling happens asynchronously the second authority producing block 296346 still had the same transaction in the pool and tried to import it.
4. Now the nonce is correct, so that check passes, but it should fail on fee payment (since the account does not exist)
5. I believe though on Kusama there is some issue with fees, or due to low congestions they are not really present, which means that the transaction was still included (CC @kianenigma)
6. The transaction failed and produced another `ReapedAccount` event. I believe that was reported by @shawntabrizi already, no? (i.e. we should not really produce that event).

Now what I don't yet understand is how is it possible that the transaction is included twice in 296346 - that would mean that it's either present twice in the transaction pool, or was returned twice by the `pending` iterator, neither of these should be a case, so I'll try to figure out what went wrong here.

**Comment by tomusdrw** [comment]
I think by no means it's a bug in `tools`, and we should probably move it to `substrate` repo. Confirming that with @jacogr now.

**Comment by joepetrowski** [comment]
> The first inclusion (block 296345) caused the balance to drop below ED

Stupid oversight on my part, working too late. I thought it was weird that Polkascan showed 3 tx for that account but only 2 in 296346. But of course the URL is based on the tx hash and that points to 296346.

So I think your order of events is correct in that the author who built on block 296345

1. Didn't realize that this tx had already been included in a block in the chain it was extending, and
2. Added the same tx twice in the same block.

Agree that this belongs in the Substrate repo.

**Comment by joepetrowski** [comment]
I think this is closed with substrate 4924
